Style/Documentation:
  Exclude:
    - lib/*/version.rb
    - spec/**/*.rb

Style/MethodName:
  Exclude:
    # XQuery method should be CamelCase
    - lib/xquery.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
